### ISSUE TITLE
Improve test coverage for published data

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-buildings#316] opened 2019-06-18 22:10 UTC
### User Story

In order to have consistent testing of the DB as a LDA I want improve test coverage over the published dataset. 

#### Acceptance Criteria
- [ ] Improve test coverage for published data
- [ ] Update PGtap scripts to test more published data

**Add an _Assignee_, _Milestone_, _Release_ and any relevant _Labels_.**

**Comment by dwsilk** [comment] 2020-01-28 08:49
Duplicate of #273

**Closed by dwsilk** 2020-01-28 08:49 UTC
Labels: duplicate
